/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import javax.swing.JOptionPane;
import modelo.Producto;
import modelo.Pedido;
/**
 *
 * @author SebastianCodena
 */
public class ChineseFood extends javax.swing.JFrame {
Producto Sushi = new Producto("Sushi",10.0,15);
Producto Ramen = new Producto("Ramen",8.5,15);
Producto  Dumplins = new Producto("Dumplins",7.0,15);
Producto TedeJazmin = new Producto("Te de Jazmin",10.0,15);
Producto Cocacola = new Producto("Cocacola",1.5,15);
Pedido Pedido = new Pedido();

    /**
     * Creates new form ChineseFood
     */
    public ChineseFood() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Anadir1 = new javax.swing.JButton();
        Contador1 = new javax.swing.JLabel();
        Eliminar1 = new javax.swing.JButton();
        Anadir2 = new javax.swing.JButton();
        Contador2 = new javax.swing.JLabel();
        Eliminar2 = new javax.swing.JButton();
        Anadir3 = new javax.swing.JButton();
        Contador3 = new javax.swing.JLabel();
        Eliminar3 = new javax.swing.JButton();
        Anadir4 = new javax.swing.JButton();
        Contador4 = new javax.swing.JLabel();
        Eliminar4 = new javax.swing.JButton();
        Anadir5 = new javax.swing.JButton();
        Eliminar5 = new javax.swing.JButton();
        Contador5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jLabel10.setText("jLabel10");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Bebidas");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu Chinese.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        Anadir1.setBackground(new java.awt.Color(0, 0, 0));
        Anadir1.setForeground(new java.awt.Color(255, 255, 255));
        Anadir1.setText("Añadir");
        Anadir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Anadir1ActionPerformed(evt);
            }
        });

        Contador1.setBackground(new java.awt.Color(255, 255, 255));
        Contador1.setForeground(new java.awt.Color(255, 255, 255));
        Contador1.setText("0");

        Eliminar1.setBackground(new java.awt.Color(0, 0, 0));
        Eliminar1.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar1.setText("Eliminar");
        Eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar1ActionPerformed(evt);
            }
        });

        Anadir2.setBackground(new java.awt.Color(0, 0, 0));
        Anadir2.setForeground(new java.awt.Color(255, 255, 255));
        Anadir2.setText("Añadir");
        Anadir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Anadir2ActionPerformed(evt);
            }
        });

        Contador2.setBackground(new java.awt.Color(255, 255, 255));
        Contador2.setForeground(new java.awt.Color(255, 255, 255));
        Contador2.setText("0");

        Eliminar2.setBackground(new java.awt.Color(0, 0, 0));
        Eliminar2.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar2.setText("Eliminar");
        Eliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar2ActionPerformed(evt);
            }
        });

        Anadir3.setBackground(new java.awt.Color(0, 0, 0));
        Anadir3.setForeground(new java.awt.Color(255, 255, 255));
        Anadir3.setText("Añadir");
        Anadir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Anadir3ActionPerformed(evt);
            }
        });

        Contador3.setBackground(new java.awt.Color(255, 255, 255));
        Contador3.setForeground(new java.awt.Color(255, 255, 255));
        Contador3.setText("0");

        Eliminar3.setBackground(new java.awt.Color(0, 0, 0));
        Eliminar3.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar3.setText("Eliminar");
        Eliminar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar3ActionPerformed(evt);
            }
        });

        Anadir4.setBackground(new java.awt.Color(0, 0, 0));
        Anadir4.setForeground(new java.awt.Color(255, 255, 255));
        Anadir4.setText("Añadir");
        Anadir4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Anadir4ActionPerformed(evt);
            }
        });

        Contador4.setBackground(new java.awt.Color(255, 255, 255));
        Contador4.setForeground(new java.awt.Color(255, 255, 255));
        Contador4.setText("0");

        Eliminar4.setBackground(new java.awt.Color(0, 0, 0));
        Eliminar4.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar4.setText("Eliminar");
        Eliminar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar4ActionPerformed(evt);
            }
        });

        Anadir5.setBackground(new java.awt.Color(0, 0, 0));
        Anadir5.setForeground(new java.awt.Color(255, 255, 255));
        Anadir5.setText("Añadir");
        Anadir5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Anadir5ActionPerformed(evt);
            }
        });

        Eliminar5.setBackground(new java.awt.Color(0, 0, 0));
        Eliminar5.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar5.setText("Eliminar");
        Eliminar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar5ActionPerformed(evt);
            }
        });

        Contador5.setBackground(new java.awt.Color(255, 255, 255));
        Contador5.setForeground(new java.awt.Color(255, 255, 255));
        Contador5.setText("0");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Pedir Orden");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/teDeJazmin.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sushi.jpg"))); // NOI18N
        jLabel4.setText("jLabel3");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ramen.jpg"))); // NOI18N
        jLabel5.setText("jLabel3");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Coca_Cola_Flasche_-_Original_Taste.jpg"))); // NOI18N
        jLabel6.setText("jLabel3");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Dumplins.jpg"))); // NOI18N
        jLabel7.setText("jLabel3");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nombre: Sushi Roll ");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Descripción: Rollos de arroz rellenos, empanizados y fritos con salsa de soya.");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Platos a la carta");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nombre: Ramen Tradicional ");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Descripción: Caldo con fideos, huevo cocido, carne y vegetales frescos.");

        jLabel14.setText("jLabel14");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Descripción corta: Empanaditas de carne y vegetales, con de salsa agridulce.");

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Nombre: Dumplings");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Bebidas");

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Nombre: Té de Jazmín");

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Descripción corta: Infusión tradicional china");

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Nombre:CocaCola");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)))
                            .addComponent(jLabel11)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jButton2)
                                .addGap(239, 239, 239)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Contador3)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(Anadir3)
                                                .addGap(24, 24, 24)))
                                        .addGap(18, 18, 18)
                                        .addComponent(Eliminar3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Anadir2)
                                        .addGap(18, 18, 18)
                                        .addComponent(Contador2)
                                        .addGap(18, 18, 18)
                                        .addComponent(Eliminar2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Anadir1)
                                        .addGap(18, 18, 18)
                                        .addComponent(Contador1)
                                        .addGap(18, 18, 18)
                                        .addComponent(Eliminar1)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel17)
                    .addComponent(jLabel20)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Anadir4)
                        .addGap(18, 18, 18)
                        .addComponent(Contador4)
                        .addGap(18, 18, 18)
                        .addComponent(Eliminar4))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Anadir5)
                        .addGap(18, 18, 18)
                        .addComponent(Contador5)
                        .addGap(18, 18, 18)
                        .addComponent(Eliminar5)))
                .addGap(11, 11, 11))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(39, 39, 39))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(14, 14, 14)))
                        .addComponent(jLabel11)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(Anadir2)
                                    .addComponent(Eliminar2)
                                    .addComponent(Contador2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Anadir4)
                                    .addComponent(Contador4)
                                    .addComponent(Eliminar4)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Anadir1)
                            .addComponent(Contador1)
                            .addComponent(Eliminar1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addGap(63, 63, 63)))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Anadir5)
                                    .addComponent(Contador5)
                                    .addComponent(Eliminar5)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addComponent(Anadir3)
                            .addComponent(Eliminar3)
                            .addComponent(Contador3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Anadir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Anadir1ActionPerformed
        boolean comprado = Sushi.comprar(1);
        if (comprado){
            int cantidad = Integer.parseInt(Contador1.getText());
            cantidad ++;
            
            
                Contador1.setText(String.valueOf(cantidad)); 
                Pedido.agregarProducto(Sushi, 1);
       }else{
           JOptionPane.showMessageDialog(null,"No hay Sushi disponible");
       }
    }//GEN-LAST:event_Anadir1ActionPerformed

    private void Anadir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Anadir2ActionPerformed
         boolean comprado = Ramen.comprar(1);
        if (comprado){
            int cantidad = Integer.parseInt(Contador2.getText());
            cantidad ++;
            
            
                Contador2.setText(String.valueOf(cantidad)); 
                Pedido.agregarProducto(Ramen, 1);
       }else{
           JOptionPane.showMessageDialog(null,"No hay Ramen disponible");
       }
    }//GEN-LAST:event_Anadir2ActionPerformed

    private void Anadir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Anadir3ActionPerformed
        boolean comprado = Dumplins.comprar(1);
        if (comprado){
            int cantidad = Integer.parseInt(Contador3.getText());
            cantidad ++;
            
            
                Contador3.setText(String.valueOf(cantidad)); 
                Pedido.agregarProducto(Dumplins, 1);
       }else{
           JOptionPane.showMessageDialog(null,"No hay Dumplins disponible");
       }
    }//GEN-LAST:event_Anadir3ActionPerformed

    private void Anadir4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Anadir4ActionPerformed
        boolean comprado = TedeJazmin.comprar(1);
        if (comprado){
            int cantidad = Integer.parseInt(Contador4.getText());
            cantidad ++;
            
            
                Contador4.setText(String.valueOf(cantidad)); 
                Pedido.agregarProducto(TedeJazmin, 1);
       }else{
           JOptionPane.showMessageDialog(null,"No hay TedeJazmin disponible");
       }
    }//GEN-LAST:event_Anadir4ActionPerformed

    private void Anadir5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Anadir5ActionPerformed
        boolean comprado = Cocacola.comprar(1);
        if (comprado){
            int cantidad = Integer.parseInt(Contador5.getText());
            cantidad ++;
            
            
                Contador5.setText(String.valueOf(cantidad)); 
                Pedido.agregarProducto(Cocacola, 1);
       }else{
           JOptionPane.showMessageDialog(null,"No hay Cocacola disponible");
       }
    }//GEN-LAST:event_Anadir5ActionPerformed

    private void Eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar1ActionPerformed
        int cantidad = Integer.parseInt(Contador1.getText());

             if(cantidad > 0){

                    cantidad--;

                Contador1.setText(String.valueOf(cantidad));
    }
    }//GEN-LAST:event_Eliminar1ActionPerformed

    private void Eliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar2ActionPerformed
        int cantidad = Integer.parseInt(Contador2.getText());

             if(cantidad > 0){

                    cantidad--;

                Contador2.setText(String.valueOf(cantidad));
    }
    }//GEN-LAST:event_Eliminar2ActionPerformed

    private void Eliminar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar3ActionPerformed
       int cantidad = Integer.parseInt(Contador3.getText());

             if(cantidad > 0){

                    cantidad--;

                Contador3.setText(String.valueOf(cantidad));
    }
    }//GEN-LAST:event_Eliminar3ActionPerformed

    private void Eliminar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar4ActionPerformed
        int cantidad = Integer.parseInt(Contador4.getText());

             if(cantidad > 0){

                    cantidad--;

                Contador4.setText(String.valueOf(cantidad));
    }
    }//GEN-LAST:event_Eliminar4ActionPerformed

    private void Eliminar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar5ActionPerformed
        int cantidad = Integer.parseInt(Contador5.getText());

             if(cantidad > 0){

                    cantidad--;

                Contador5.setText(String.valueOf(cantidad));
    }
    }//GEN-LAST:event_Eliminar5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         PedidoSpanish ventana = new PedidoSpanish();
        
        ventana.mostrarPedido(Pedido.getResumen());
        ventana.recibirTotal(Pedido.getTotalConIVA());
        ventana.establecerOrigen("Chinese");
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         Comidas menu = new Comidas();
    menu.setVisible(true);
    
    this.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChineseFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChineseFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChineseFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChineseFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChineseFood().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Anadir1;
    private javax.swing.JButton Anadir2;
    private javax.swing.JButton Anadir3;
    private javax.swing.JButton Anadir4;
    private javax.swing.JButton Anadir5;
    private javax.swing.JLabel Contador1;
    private javax.swing.JLabel Contador2;
    private javax.swing.JLabel Contador3;
    private javax.swing.JLabel Contador4;
    private javax.swing.JLabel Contador5;
    private javax.swing.JButton Eliminar1;
    private javax.swing.JButton Eliminar2;
    private javax.swing.JButton Eliminar3;
    private javax.swing.JButton Eliminar4;
    private javax.swing.JButton Eliminar5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
