/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author SebastianCodena
 */
import java.io.*;
public class Comidas extends javax.swing.JFrame {

    /**
     * Creates new form Comidas
     */
    public Comidas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRestEspanol = new javax.swing.JButton();
        btnRestChino = new javax.swing.JButton();
        btnRestItalia = new javax.swing.JButton();
        btnRestEcuador = new javax.swing.JButton();
        btnCerrarCaja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        btnRestEspanol.setBackground(new java.awt.Color(0, 0, 0));
        btnRestEspanol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Spanish.png"))); // NOI18N
        btnRestEspanol.setText("jButton2");
        btnRestEspanol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestEspanolActionPerformed(evt);
            }
        });

        btnRestChino.setBackground(new java.awt.Color(0, 0, 0));
        btnRestChino.setForeground(new java.awt.Color(255, 255, 255));
        btnRestChino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ChineseFod.png"))); // NOI18N
        btnRestChino.setText("jButton1");
        btnRestChino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestChinoActionPerformed(evt);
            }
        });

        btnRestItalia.setBackground(new java.awt.Color(0, 0, 0));
        btnRestItalia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Italian.png"))); // NOI18N
        btnRestItalia.setText("jButton4");
        btnRestItalia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestItaliaActionPerformed(evt);
            }
        });

        btnRestEcuador.setBackground(new java.awt.Color(0, 0, 0));
        btnRestEcuador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ecuadorian.png"))); // NOI18N
        btnRestEcuador.setText("jButton3");
        btnRestEcuador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestEcuadorActionPerformed(evt);
            }
        });

        btnCerrarCaja.setBackground(new java.awt.Color(51, 51, 51));
        btnCerrarCaja.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarCaja.setText("Cerrar Caja");
        btnCerrarCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarCajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRestChino, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRestEcuador, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRestItalia, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRestEspanol, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(43, 43, 43))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(btnCerrarCaja)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnRestEspanol, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRestChino, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCerrarCaja)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRestItalia, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRestEcuador, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRestChinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestChinoActionPerformed
        ChineseFood menu = new ChineseFood();

            menu.setVisible(true);

                this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnRestChinoActionPerformed

    private void btnRestEspanolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestEspanolActionPerformed
       SpanishFood menu = new SpanishFood();

            menu.setVisible(true);

                this.dispose(); 
    }//GEN-LAST:event_btnRestEspanolActionPerformed

    private void btnRestEcuadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestEcuadorActionPerformed
        EcuadorianFood menu = new EcuadorianFood();

            menu.setVisible(true);

                this.dispose(); 
    }//GEN-LAST:event_btnRestEcuadorActionPerformed

    private void btnRestItaliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestItaliaActionPerformed
        ItalianFood menu = new ItalianFood();

            menu.setVisible(true);

                this.dispose(); 
    }//GEN-LAST:event_btnRestItaliaActionPerformed

    private void btnCerrarCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarCajaActionPerformed
        try {
        double ingresosTotales = modelo.ReporteDiario.obtenerTotalCaja(); 
        
        if (ingresosTotales == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "No se pueden registrar cierres de caja ni generar reportes porque no hay ventas realizadas el día de hoy.", 
                    "Caja Vacía", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return; 
        }
            
            

      
        String masVendidoRestaurante = modelo.ReporteDiario.obtenerRestauranteMayorVenta();
        String menosVendidoRestaurante = modelo.ReporteDiario.obtenerRestauranteMenorVenta();
        String productoEstrella = modelo.ReporteDiario.obtenerProductoMasVendido();
        String historialVentas = modelo.ReporteDiario.obtenerReporteGeneral();

        StringBuilder reporteCompleto = new StringBuilder();
        reporteCompleto.append("=================================================\n");
        reporteCompleto.append("      REPORTE DE VENTAS Y CIERRE DE CAJA          \n");
        reporteCompleto.append("=================================================\n\n");
        reporteCompleto.append("1. RENDIMIENTO DE RESTAURANTES:\n");
        reporteCompleto.append("   -> Mayor volumen de venta: ").append(masVendidoRestaurante).append("\n");
        reporteCompleto.append("   -> Menor volumen de venta: ").append(menosVendidoRestaurante).append("\n\n");
        reporteCompleto.append("2. PREFERENCIAS DEL CONSUMIDOR:\n");
        reporteCompleto.append("   -> Producto más vendido: ").append(productoEstrella).append("\n\n");
        reporteCompleto.append("3. BALANCE ECONÓMICO GLOBAL:\n");
        reporteCompleto.append("   -> Total Recaudado en Caja: $").append(String.format("%.2f", ingresosTotales)).append("\n");
        reporteCompleto.append("=================================================\n\n");
        reporteCompleto.append(historialVentas);;
        
     
        java.io.FileWriter archivoReporte = new java.io.FileWriter("reporte_ventas_diarias.txt");
        java.io.PrintWriter escribir = new java.io.PrintWriter(archivoReporte);
        escribir.print(reporteCompleto.toString());
        escribir.close();

        javax.swing.JTextArea areaTexto = new javax.swing.JTextArea(reporteCompleto.toString());
        areaTexto.setEditable(false); 
        areaTexto.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12)); 
        
        javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(areaTexto);
        scrollPane.setPreferredSize(new java.awt.Dimension(500, 400));

      

    
        javax.swing.JOptionPane.showMessageDialog(this, 
                scrollPane, 
                "Cierre de Caja - Reporte Diario", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Error al procesar el cierre de caja o escribir el archivo.", 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnCerrarCajaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarCaja;
    private javax.swing.JButton btnRestChino;
    private javax.swing.JButton btnRestEcuador;
    private javax.swing.JButton btnRestEspanol;
    private javax.swing.JButton btnRestItalia;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
