/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import javax.swing.JOptionPane;
import modelo.Producto;
import modelo.Pedido;
/**
 *
 * @author SebastianCodena
 */
public class EcuadorianFood extends javax.swing.JFrame {
    Producto SecodePollo = new Producto("Seco de Pollo",3.0,15);
    Producto Encebollado = new Producto("Encebollado",3.0,15);
    Producto SecodeCarne = new Producto("Seco de Carne",3.0,15);
    Producto Horchata = new Producto("Horchata",2.0,15);
    Producto Cocacola = new Producto("Cocacola",5.0,15);
    Pedido Pedido = new Pedido();

    /**
     * Creates new form EcuadorianFood
     */
    public EcuadorianFood() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnAnadir1 = new javax.swing.JButton();
        Contador1 = new javax.swing.JLabel();
        btnEliminar1 = new javax.swing.JButton();
        btnAnadir2 = new javax.swing.JButton();
        btnEliminar2 = new javax.swing.JButton();
        Contador2 = new javax.swing.JLabel();
        btnAnadir3 = new javax.swing.JButton();
        btnEliminar3 = new javax.swing.JButton();
        Contador3 = new javax.swing.JLabel();
        btnAnadir4 = new javax.swing.JButton();
        Contador4 = new javax.swing.JLabel();
        btnEliminar4 = new javax.swing.JButton();
        btnAnadir5 = new javax.swing.JButton();
        Contador5 = new javax.swing.JLabel();
        btnEliminar5 = new javax.swing.JButton();
        btnPedirOrden = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu Ecuadorian.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        btnAnadir1.setBackground(new java.awt.Color(51, 51, 51));
        btnAnadir1.setForeground(new java.awt.Color(255, 255, 255));
        btnAnadir1.setText("Añadir");
        btnAnadir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadir1ActionPerformed(evt);
            }
        });

        Contador1.setForeground(new java.awt.Color(255, 255, 255));
        Contador1.setText("0");

        btnEliminar1.setBackground(new java.awt.Color(51, 51, 51));
        btnEliminar1.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar1.setText("Eliminar");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        btnAnadir2.setBackground(new java.awt.Color(51, 51, 51));
        btnAnadir2.setForeground(new java.awt.Color(255, 255, 255));
        btnAnadir2.setText("Añadir");
        btnAnadir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadir2ActionPerformed(evt);
            }
        });

        btnEliminar2.setBackground(new java.awt.Color(51, 51, 51));
        btnEliminar2.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar2.setText("Eliminar");
        btnEliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar2ActionPerformed(evt);
            }
        });

        Contador2.setForeground(new java.awt.Color(255, 255, 255));
        Contador2.setText("0");

        btnAnadir3.setBackground(new java.awt.Color(51, 51, 51));
        btnAnadir3.setForeground(new java.awt.Color(255, 255, 255));
        btnAnadir3.setText("Añadir");
        btnAnadir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadir3ActionPerformed(evt);
            }
        });

        btnEliminar3.setBackground(new java.awt.Color(51, 51, 51));
        btnEliminar3.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar3.setText("Eliminar");
        btnEliminar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar3ActionPerformed(evt);
            }
        });

        Contador3.setForeground(new java.awt.Color(255, 255, 255));
        Contador3.setText("0");

        btnAnadir4.setBackground(new java.awt.Color(51, 51, 51));
        btnAnadir4.setForeground(new java.awt.Color(255, 255, 255));
        btnAnadir4.setText("Añadir");
        btnAnadir4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadir4ActionPerformed(evt);
            }
        });

        Contador4.setForeground(new java.awt.Color(255, 255, 255));
        Contador4.setText("0");

        btnEliminar4.setBackground(new java.awt.Color(51, 51, 51));
        btnEliminar4.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar4.setText("Eliminar");
        btnEliminar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar4ActionPerformed(evt);
            }
        });

        btnAnadir5.setBackground(new java.awt.Color(51, 51, 51));
        btnAnadir5.setForeground(new java.awt.Color(255, 255, 255));
        btnAnadir5.setText("Añadir");
        btnAnadir5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadir5ActionPerformed(evt);
            }
        });

        Contador5.setForeground(new java.awt.Color(255, 255, 255));
        Contador5.setText("0");

        btnEliminar5.setBackground(new java.awt.Color(51, 51, 51));
        btnEliminar5.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar5.setText("Eliminar");
        btnEliminar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar5ActionPerformed(evt);
            }
        });

        btnPedirOrden.setBackground(new java.awt.Color(51, 51, 51));
        btnPedirOrden.setForeground(new java.awt.Color(255, 255, 255));
        btnPedirOrden.setText("Pedir Orden");
        btnPedirOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedirOrdenActionPerformed(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(51, 51, 51));
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/secodecarne.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Secodepollo.jpg"))); // NOI18N
        jLabel3.setText("jLabel1");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/encebollado.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/horchata.jpg"))); // NOI18N
        jLabel6.setText("jLabel5");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Coca_Cola_Flasche_-_Original_Taste.jpg"))); // NOI18N
        jLabel7.setText("jLabel1");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nombre: Seco de Pollo");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Descripción: Pollo guisado, servido con arroz amarillo y aguacate.");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Platos a la carta");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Bebidas");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nombre: Encebollado de Pescado");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Descripción: Caldo de albacora con yuca, cebolla, cilantro y limón.");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nombre: Seco de Carne");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Descripción: Guiso tradicional con arroz, maduro frito y aguacate.");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Nombre: Horchata Lojana");

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Descripción: Infusión de hierbas y flores, con un toque de limón.");

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Nombre: Cocacola");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPedirOrden)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAnadir1)
                                .addGap(18, 18, 18)
                                .addComponent(Contador1)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnVolver, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(222, 222, 222)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel12)
                                                            .addComponent(jLabel14)
                                                            .addComponent(jLabel13)))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel10)
                                                        .addGap(176, 176, 176)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(btnAnadir3)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(Contador3))
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(btnAnadir2)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(Contador2, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                .addGap(26, 26, 26)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnEliminar3)
                                                    .addComponent(btnEliminar2)))))
                                    .addComponent(jLabel11))
                                .addGap(176, 176, 176)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnAnadir4)
                                        .addGap(18, 18, 18)
                                        .addComponent(Contador4)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEliminar4))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnAnadir5)
                                        .addGap(18, 18, 18)
                                        .addComponent(Contador5)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEliminar5)))))
                        .addContainerGap(25, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(btnVolver)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAnadir1)
                            .addComponent(Contador1)
                            .addComponent(btnEliminar1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel19))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel9))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14)))
                        .addGap(37, 37, 37)
                        .addComponent(btnPedirOrden)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel10)
                                .addGap(14, 14, 14)
                                .addComponent(jLabel12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAnadir2)
                                    .addComponent(Contador2)
                                    .addComponent(btnEliminar2)
                                    .addComponent(btnAnadir4)
                                    .addComponent(Contador4)
                                    .addComponent(btnEliminar4))))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAnadir5)
                                    .addComponent(Contador5)
                                    .addComponent(btnEliminar5)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAnadir3)
                                    .addComponent(Contador3)
                                    .addComponent(btnEliminar3))))
                        .addGap(165, 165, 165))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnadir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadir1ActionPerformed
        boolean comprado = SecodePollo.comprar(1);
       
       if(comprado){
         int cantidad = Integer.parseInt(Contador1.getText());

            cantidad++;

                Contador1.setText(String.valueOf(cantidad)); 
                Pedido.agregarProducto(SecodePollo, 1);
       }else{
           JOptionPane.showMessageDialog(null,"No hay Seco de Pollo disponible");
       }
        
        
    }//GEN-LAST:event_btnAnadir1ActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        int cantidad = Integer.parseInt(Contador1.getText());

             if(cantidad > 0){

                    cantidad--;

                Contador1.setText(String.valueOf(cantidad));
    }
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void btnAnadir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadir2ActionPerformed
         boolean comprado = Encebollado.comprar(1);
       
       if(comprado){
         int cantidad = Integer.parseInt(Contador2.getText());

            cantidad++;

                Contador2.setText(String.valueOf(cantidad)); 
                Pedido.agregarProducto(Encebollado, 1);
       }else{
           JOptionPane.showMessageDialog(null,"No hay Encebollado disponible");
       }
        
    }//GEN-LAST:event_btnAnadir2ActionPerformed

    private void btnEliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar2ActionPerformed
         int cantidad = Integer.parseInt(Contador2.getText());

             if(cantidad > 0){

                    cantidad--;

                Contador2.setText(String.valueOf(cantidad));
    }
    }//GEN-LAST:event_btnEliminar2ActionPerformed

    private void btnAnadir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadir3ActionPerformed
         boolean comprado = SecodeCarne.comprar(1);
       
       if(comprado){
         int cantidad = Integer.parseInt(Contador3.getText());

            cantidad++;

                Contador3.setText(String.valueOf(cantidad)); 
                Pedido.agregarProducto(SecodeCarne, 1);
       }else{
           JOptionPane.showMessageDialog(null,"No hay SecodeCarne disponible");
       }
    }//GEN-LAST:event_btnAnadir3ActionPerformed

    private void btnEliminar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar3ActionPerformed
       int cantidad = Integer.parseInt(Contador3.getText());

             if(cantidad > 0){

                    cantidad--;

                Contador3.setText(String.valueOf(cantidad));
    }
    }//GEN-LAST:event_btnEliminar3ActionPerformed

    private void btnAnadir4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadir4ActionPerformed
        boolean comprado = Horchata.comprar(1);
       
       if(comprado){
         int cantidad = Integer.parseInt(Contador4.getText());

            cantidad++;

                Contador4.setText(String.valueOf(cantidad)); 
                Pedido.agregarProducto(Horchata, 1);
       }else{
           JOptionPane.showMessageDialog(null,"No hay Horchata disponible");
       }
    }//GEN-LAST:event_btnAnadir4ActionPerformed

    private void btnEliminar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar4ActionPerformed
       int cantidad = Integer.parseInt(Contador4.getText());

             if(cantidad > 0){

                    cantidad--;

                Contador4.setText(String.valueOf(cantidad));
    }
    }//GEN-LAST:event_btnEliminar4ActionPerformed

    private void btnAnadir5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadir5ActionPerformed
         boolean comprado = Cocacola.comprar(1);
       
       if(comprado){
         int cantidad = Integer.parseInt(Contador5.getText());

            cantidad++;

                Contador5.setText(String.valueOf(cantidad)); 
                Pedido.agregarProducto(Cocacola, 1);
       }else{
           JOptionPane.showMessageDialog(null,"No hay CocaCola disponible");
       }
    }//GEN-LAST:event_btnAnadir5ActionPerformed

    private void btnEliminar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar5ActionPerformed
        int cantidad = Integer.parseInt(Contador5.getText());

             if(cantidad > 0){

                    cantidad--;

                Contador5.setText(String.valueOf(cantidad));
    }
    }//GEN-LAST:event_btnEliminar5ActionPerformed

    private void btnPedirOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedirOrdenActionPerformed
          PedidoSpanish ventana = new PedidoSpanish();
        
        ventana.mostrarPedido(Pedido.getResumen());
        ventana.recibirTotal(Pedido.getTotalConIVA());
        ventana.recibirSubtotalYIva(Pedido.getSubtotal(), Pedido.getIVA());
        ventana.setVisible(true);
        ventana.establecerOrigen("Ecuadorian");
        this.dispose();
    }//GEN-LAST:event_btnPedirOrdenActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
       Comidas menu = new Comidas();
    menu.setVisible(true);
    
    this.dispose();

    }//GEN-LAST:event_btnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Contador1;
    private javax.swing.JLabel Contador2;
    private javax.swing.JLabel Contador3;
    private javax.swing.JLabel Contador4;
    private javax.swing.JLabel Contador5;
    private javax.swing.JButton btnAnadir1;
    private javax.swing.JButton btnAnadir2;
    private javax.swing.JButton btnAnadir3;
    private javax.swing.JButton btnAnadir4;
    private javax.swing.JButton btnAnadir5;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnEliminar2;
    private javax.swing.JButton btnEliminar3;
    private javax.swing.JButton btnEliminar4;
    private javax.swing.JButton btnEliminar5;
    private javax.swing.JButton btnPedirOrden;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
