/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;
import modelo.Pedido;
import vista.ChineseFood;
import vista.Comidas;
import vista.EcuadorianFood;
import vista.ItalianFood;
import vista.SpanishFood;

/**
 *
 * @author SebastianCodena
 */
public class PedidoSpanish extends javax.swing.JFrame {
double totalPedido;
    double subtotalPedido; 
    double ivaPedido;    
    String resumenTexto;   
Pedido Pedido = new Pedido();
String restauranteOrigen;
    /**
     * Creates new form PedidoSpanishFood
     */
    public PedidoSpanish() {
        initComponents();
    }
     public void mostrarPedido(String texto){

        txtPedidos.setText(texto);
        this.resumenTexto = texto;
    }
    public void recibirTotal(double total){

    totalPedido = total;
}
    public void recibirSubtotalYIva(double subtotal, double iva){
        this.subtotalPedido = subtotal;
        this.ivaPedido = iva;
    }
public void establecerOrigen(String restaurante) {
    this.restauranteOrigen = restaurante;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPedidos = new javax.swing.JTextArea();
        btnRecogerEnCaja = new javax.swing.JButton();
        btnPedirDomicilio = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        btnRegresar.setBackground(new java.awt.Color(51, 51, 51));
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        txtPedidos.setEditable(false);
        txtPedidos.setBackground(new java.awt.Color(204, 204, 204));
        txtPedidos.setColumns(20);
        txtPedidos.setRows(5);
        jScrollPane1.setViewportView(txtPedidos);

        btnRecogerEnCaja.setBackground(new java.awt.Color(51, 51, 51));
        btnRecogerEnCaja.setForeground(new java.awt.Color(255, 255, 255));
        btnRecogerEnCaja.setText("Recoger en caja ");
        btnRecogerEnCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecogerEnCajaActionPerformed(evt);
            }
        });

        btnPedirDomicilio.setBackground(new java.awt.Color(51, 51, 51));
        btnPedirDomicilio.setForeground(new java.awt.Color(255, 255, 255));
        btnPedirDomicilio.setText("Pedir a domicilio(Delivery)");
        btnPedirDomicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedirDomicilioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnRegresar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(btnRecogerEnCaja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(btnPedirDomicilio)
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnRegresar)))
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPedirDomicilio)
                    .addComponent(btnRecogerEnCaja))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRecogerEnCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecogerEnCajaActionPerformed
        String nombreCliente = javax.swing.JOptionPane.showInputDialog("Ingrese el nombre del cliente para el retiro:");
    
    if (nombreCliente == null || nombreCliente.trim().isEmpty()) {
        nombreCliente = "Cliente Local Anónimo";
    }

    javax.swing.JOptionPane.showMessageDialog(null, "Pedido solicitado\nGracias por su compra");
    
    
    modelo.ReporteDiario.registrarVenta(nombreCliente, totalPedido, resumenTexto, restauranteOrigen);
    
 
    Comidas menuPrincipal = new Comidas();
    menuPrincipal.setVisible(true);
    this.dispose();


    }//GEN-LAST:event_btnRecogerEnCajaActionPerformed

    private void btnPedirDomicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedirDomicilioActionPerformed
       
        DeliveryVista v = new DeliveryVista();
        v.recibirTotal(totalPedido);
        
  
        v.recibirDatos(resumenTexto, subtotalPedido, ivaPedido); 
        v.recibirOrigen(restauranteOrigen);
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPedirDomicilioActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
     if (restauranteOrigen != null) {
        switch (restauranteOrigen) {
            case "Spanish":
                SpanishFood esp = new SpanishFood();
                esp.setVisible(true);
                break;
            case "Ecuadorian":
                EcuadorianFood ecu = new EcuadorianFood();
                ecu.setVisible(true);
                break;
            case "Chinese":
                ChineseFood chi = new ChineseFood();
                chi.setVisible(true);
                break;
            case "Italian":
                ItalianFood ita = new ItalianFood();
                ita.setVisible(true);
                break;
            default:
            
                Comidas menu = new Comidas();
                menu.setVisible(true);
                break;
        }
    } else {
        Comidas menu = new Comidas();
        menu.setVisible(true);
    }
    
    this.dispose(); 

    }//GEN-LAST:event_btnRegresarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPedirDomicilio;
    private javax.swing.JButton btnRecogerEnCaja;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea txtPedidos;
    // End of variables declaration//GEN-END:variables

    void txtPedido(String resumen) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
